# Build the GO binary
FROM golang:1.22 as build_sales-api
ENV CGO_ENABLED = 0
ARG BUILD_REF

# Copy the source code into the container
COPY . /service

WORKDIR /service/app/services/sales-api
RUN go build -ldflags "-X main.build=${BUILD_REF}"

FROM alpine:3.18
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S sales && \
    adduser -u 1000 -h /service -G sales -S sales \
