apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: sales-api
          resources:
            requests:
              cpu: "1500m" # I need access to 1.5 cores on the node.
              memory: 500Mi
            limits:
              cpu: "1500m" # Execute instructions 150ms/200ms on my 1.5 cores.
              memory: 500Mi